import type { PropertyListing } from "./types";

/**
 * Bundled fallback inventory — used until Supabase is connected, and as a
 * safety net if the live table is empty or unreachable. Fictional but
 * realistic Delhi NCR listings; replace with real data via supabase/schema.sql.
 */
export const SAMPLE_PROPERTIES: PropertyListing[] = [
  {
    id: "smp-01",
    title: "Sector 65 Residency",
    city: "Gurugram",
    locality: "Sector 65, Gurugram",
    propertyType: "Apartment",
    bhk: "3 BHK",
    priceCr: 2.1,
    areaSqft: 1750,
    possession: "Ready to move",
    possessionDate: null,
    intentFit: ["buy", "invest"],
    amenities: ["Clubhouse", "Gated community", "Power backup", "Kids play area"],
    highlights: "Low-density tower with east-facing units and strong rental demand.",
    reraId: "RC/REP/HARERA/GGM/2024/01",
    imageUrl: null,
    active: true,
  },
  {
    id: "smp-02",
    title: "Emerald Greens",
    city: "Gurugram",
    locality: "Sector 65, Gurugram",
    propertyType: "Apartment",
    bhk: "3 BHK",
    priceCr: 2.35,
    areaSqft: 1900,
    possession: "Ready to move",
    possessionDate: null,
    intentFit: ["buy"],
    amenities: ["Swimming pool", "Gym", "24x7 security", "Landscaped gardens"],
    highlights: "Larger carpet area than most 3 BHKs in the sector; corner units available.",
    reraId: "RC/REP/HARERA/GGM/2024/02",
    imageUrl: null,
    active: true,
  },
  {
    id: "smp-03",
    title: "Palm Court Floors",
    city: "Gurugram",
    locality: "Sector 57, Gurugram",
    propertyType: "Apartment",
    bhk: "2 BHK",
    priceCr: 1.4,
    areaSqft: 1150,
    possession: "Under construction",
    possessionDate: "Jun 2027",
    intentFit: ["buy", "rent"],
    amenities: ["Covered parking", "Park facing", "Lift"],
    highlights: "Attractive construction-linked payment plan; park-facing stack.",
    reraId: "RC/REP/HARERA/GGM/2025/03",
    imageUrl: null,
    active: true,
  },
  {
    id: "smp-04",
    title: "Meadow Villas",
    city: "Gurugram",
    locality: "Sector 82, Gurugram",
    propertyType: "Villa",
    bhk: "4 BHK",
    priceCr: 3.8,
    areaSqft: 3200,
    possession: "Ready to move",
    possessionDate: null,
    intentFit: ["buy"],
    amenities: ["Private garden", "Servant quarters", "Gated community", "Clubhouse"],
    highlights: "Corner villa with a private garden — rare at this price on NH-8 side.",
    reraId: "RC/REP/HARERA/GGM/2023/04",
    imageUrl: null,
    active: true,
  },
  {
    id: "smp-05",
    title: "Golf Extension Floors",
    city: "Gurugram",
    locality: "Golf Course Extension Road, Gurugram",
    propertyType: "Builder Floor",
    bhk: "3 BHK",
    priceCr: 1.9,
    areaSqft: 1600,
    possession: "Ready to move",
    possessionDate: null,
    intentFit: ["buy", "invest"],
    amenities: ["No shared walls", "Private terrace", "Stilt parking"],
    highlights: "Independent floor living with strong appreciation track on GCX Road.",
    reraId: "RC/REP/HARERA/GGM/2024/05",
    imageUrl: null,
    active: true,
  },
  {
    id: "smp-06",
    title: "Sports City Residency",
    city: "Noida",
    locality: "Sector 150, Noida",
    propertyType: "Apartment",
    bhk: "2 BHK",
    priceCr: 1.05,
    areaSqft: 1050,
    possession: "Ready to move",
    possessionDate: null,
    intentFit: ["invest", "buy", "rent"],
    amenities: ["Sports facilities", "Clubhouse", "Jogging track", "Swimming pool"],
    highlights: "Greenest sector in Noida; consistently high tenant demand.",
    reraId: "UPRERAPRJ2024/06",
    imageUrl: null,
    active: true,
  },
  {
    id: "smp-07",
    title: "Expressway Greens",
    city: "Noida",
    locality: "Sector 143, Noida",
    propertyType: "Apartment",
    bhk: "2 BHK",
    priceCr: 0.95,
    areaSqft: 980,
    possession: "Under construction",
    possessionDate: "Dec 2026",
    intentFit: ["invest"],
    amenities: ["Landscaped gardens", "Rainwater harvesting", "Metro nearby"],
    highlights: "Entry price on the Expressway with metro connectivity already live.",
    reraId: "UPRERAPRJ2025/07",
    imageUrl: null,
    active: true,
  },
  {
    id: "smp-08",
    title: "Riverside Heights",
    city: "Noida",
    locality: "Sector 137, Noida Expressway",
    propertyType: "Apartment",
    bhk: "3 BHK",
    priceCr: 1.6,
    areaSqft: 1450,
    possession: "Ready to move",
    possessionDate: null,
    intentFit: ["buy", "invest"],
    amenities: ["Clubhouse", "Kids play area", "Power backup"],
    highlights: "Walkable to metro; society is fully occupied with an active RWA.",
    reraId: "UPRERAPRJ2023/08",
    imageUrl: null,
    active: true,
  },
  {
    id: "smp-09",
    title: "Sector 62 Floors",
    city: "Noida",
    locality: "Sector 62, Noida",
    propertyType: "Builder Floor",
    bhk: "2 BHK",
    priceCr: 0.85,
    areaSqft: 900,
    possession: "Ready to move",
    possessionDate: null,
    intentFit: ["rent", "invest"],
    amenities: ["Metro nearby", "Covered parking"],
    highlights: "IT-hub location — dependable rental yield from corporate tenants.",
    reraId: null,
    imageUrl: null,
    active: true,
  },
  {
    id: "smp-10",
    title: "Dwarka Sector 12 Residency",
    city: "Delhi",
    locality: "Sector 12, Dwarka",
    propertyType: "Apartment",
    bhk: "2 BHK",
    priceCr: 1.1,
    areaSqft: 1100,
    possession: "Ready to move",
    possessionDate: null,
    intentFit: ["buy"],
    amenities: ["Metro nearby", "Community hall", "Market nearby"],
    highlights: "Established society two blocks from the Blue Line metro.",
    reraId: null,
    imageUrl: null,
    active: true,
  },
  {
    id: "smp-11",
    title: "Dwarka Sector 23 Residency",
    city: "Delhi",
    locality: "Sector 23, Dwarka",
    propertyType: "Apartment",
    bhk: "3 BHK",
    priceCr: 1.75,
    areaSqft: 1500,
    possession: "Ready to move",
    possessionDate: null,
    intentFit: ["buy", "invest"],
    amenities: ["Clubhouse", "Power backup", "Gated community"],
    highlights: "Spacious layout close to the upcoming Dwarka Expressway interchange.",
    reraId: null,
    imageUrl: null,
    active: true,
  },
  {
    id: "smp-12",
    title: "Greater Noida West Residency",
    city: "Greater Noida",
    locality: "Greater Noida West",
    propertyType: "Apartment",
    bhk: "2 BHK",
    priceCr: 0.65,
    areaSqft: 950,
    possession: "Under construction",
    possessionDate: "Mar 2027",
    intentFit: ["buy", "invest"],
    amenities: ["Gated community", "Kids play area", "Clubhouse"],
    highlights: "Best affordability in NCR for a first home; strong social infrastructure coming up.",
    reraId: "UPRERAPRJ2025/12",
    imageUrl: null,
    active: true,
  },
  {
    id: "smp-13",
    title: "Yamuna Expressway Plots",
    city: "Greater Noida",
    locality: "Yamuna Expressway, Greater Noida",
    propertyType: "Plot",
    bhk: null,
    priceCr: 0.55,
    areaSqft: 1500,
    possession: "Ready to move",
    possessionDate: null,
    intentFit: ["buy", "invest"],
    amenities: ["Clear title", "Gated township"],
    highlights: "Land bank play near the upcoming Noida International Airport.",
    reraId: "UPRERAPRJ2024/13",
    imageUrl: null,
    active: true,
  },
  {
    id: "smp-14",
    title: "Faridabad Sector 86 Residency",
    city: "Faridabad",
    locality: "Sector 86, Faridabad",
    propertyType: "Apartment",
    bhk: "3 BHK",
    priceCr: 1.15,
    areaSqft: 1400,
    possession: "Ready to move",
    possessionDate: null,
    intentFit: ["buy"],
    amenities: ["Gated community", "Power backup", "Park facing"],
    highlights: "Most 3 BHK space per rupee in NCR; peaceful, family-heavy society.",
    reraId: "RC/REP/HARERA/FBD/2023/14",
    imageUrl: null,
    active: true,
  },
  {
    id: "smp-15",
    title: "Indirapuram Residency",
    city: "Ghaziabad",
    locality: "Indirapuram, Ghaziabad",
    propertyType: "Apartment",
    bhk: "2 BHK",
    priceCr: 0.72,
    areaSqft: 1050,
    possession: "Ready to move",
    possessionDate: null,
    intentFit: ["buy", "rent"],
    amenities: ["Market nearby", "Covered parking", "Lift"],
    highlights: "Mature neighbourhood with everything walkable — schools, markets, hospitals.",
    reraId: null,
    imageUrl: null,
    active: true,
  },
];
